name: Biome Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  biome-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install npm
        run: npm install

      - name: Run Biome
        run: pnpm test