name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Fetch all tags
      - name: Fetch all tags
        run: git fetch --tags

      # Extract the latest tag or use a default value
      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "tag=$tag" >> $GITHUB_ENV

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install auto-changelog dependencies
      - name: Install Dependencies
        run: npm install

      # Run the changelog generation
      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat    : New Features
            fix     : Bug Fixes
            build   : Build System & Dependencies
            perf    : Performance Improvements
            docs    : Documentation
            test    : Tests
            refactor: Refactors
            chore   : Chores
            ci      : CI
            style   : Code Style
            revert  : Reverts
          default-commit-type: Other Changes
          release-name: ${{ env.tag }}
          mention-authors: true
          include-pr-links: true
          include-compare-link: true
          semver: true

      # Commit and push the changelog
      - name: Commit and Push Changelog
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD
