name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      - name: Install Dependencies
        run: npm install


      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat    : New Features
            fix     : Bug Fixes
            build   : Build System & Dependencies
            perf    : Performance Improvements
            docs    : Documentation
            test    : Tests
            refactor: Refactors
            chore   : Chores
            ci      : CI
            style   : Code Style
            revert  : Reverts
          default-commit-type: Other Changes
          release-name: auto
          mention-authors: true
          include-pr-links: true
          include-compare-link: true
          semver: true

      - name: Commit and Push Changelog
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "docs: update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD
