name: CI/CD for NPM Library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      # - name: Run tests
      #   run: pnpm test

      - name: Build the project
        run: pnpm build

      - name: Bump version and generate changelog
        id: versioning
        run: |
          git config user.name "CI/CD"
          git config user.email "cicd@github.com"
          npx standard-version --no-verify

      - name: Commit changes
        run: |
          git add .
          git commit -m "chore(release): bump version" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ReysinProject/reysin.git HEAD:main

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}